---
Gemfile:
  required:
    ':development':
      - gem: 'httparty'
      - gem: 'puppet-strings'
        git: 'https://github.com/puppetlabs/puppet-strings'
  optional:
    ':development':
      - gem: 'puppet-resource_api'
spec/spec_helper.rb:
  mock_with: ':rspec'
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  includes:
    - env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    - env: CHECK=parallel_spec
    - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.1
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
.gitignore:
  paths:
    - '/scratch/'
.pdkignore:
  paths:
    - '/scratch/'
